import test from 'node:test';import assert from 'node:assert/strict';import {spawn}from'node:child_process';
const origin='http://localhost:4318';const child=spawn(process.execPath,['server/index.mjs'],{env:{...process.env,PORT:'4318',APP_URL:origin,TEST_DB:':memory:',DATABASE_URL:'',NODE_ENV:'development'},stdio:['ignore','pipe','pipe']});
await new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(Error('Server startup timed out')),15000);child.stdout.on('data',d=>{if(d.toString().includes('BREGIS local')){clearTimeout(t);resolve();}});child.on('exit',c=>reject(Error('Server exit '+c)));});
let cookie='';async function req(url,method='GET',data,customOrigin=origin){const r=await fetch(origin+url,{method,headers:{'content-type':'application/json',origin:customOrigin,...(cookie?{cookie}:{})},...(data?{body:JSON.stringify(data)}:{})});if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];return r;}
test('anonymous cannot access profile or administration',async()=>{assert.equal((await req('/api/profile')).status,401);assert.equal((await req('/api/admin/articles')).status,401);});
test('CSRF protection rejects unexpected origin',async()=>assert.equal((await req('/api/local-login','POST',{},'https://evil.example')).status,403));
test('all collapsed complex service content and illustrations are present',async()=>{const a=await(await req('/api/articles/wiki-Complex_services')).json();assert.ok(a.body.includes('суммарная стоимость'));assert.equal((a.html.match(/<img /g)||[]).length,11);assert.ok(!/>Показать<|>Скрыть<|onclick=|display: none/.test(a.html));});
test('public article contains indexable server-rendered text',async()=>{const html=await(await req('/learn/wiki-Complex_services')).text();assert.ok(html.includes('суммарная стоимость'));assert.ok(html.includes('rel="canonical"'));});
test('end-to-end attempt retains progress and awards once on replay',async()=>{assert.equal((await req('/api/local-login','POST',{})).status,200);const a=await(await req('/api/quests/weblab-basics/start','POST',{})).json();assert.ok(!('answer'in a.questions[0]));await req('/api/attempts/'+a.id,'PUT',{answers:[0,[0,1],0]});let result=await(await req('/api/attempts/'+a.id+'/finish','POST',{})).json();assert.equal(result.score,100);await Promise.all(Array.from({length:5},()=>req('/api/attempts/'+a.id+'/finish','POST',{})));const p=await(await req('/api/profile')).json();assert.equal(p.xp,120);assert.equal(p.level,2);});
test('draft materials are excluded from direct access and search',async()=>{const c=await(await req('/api/admin/articles','POST',{})).json();assert.equal((await req('/api/articles/'+c.id)).status,404);const s=await(await req('/api/catalog?q='+encodeURIComponent('Новый материал'))).json();assert.ok(!s.items.some(a=>a.id===c.id));});
test.after(()=>child.kill());
