import express from 'express';import session from 'express-session';import helmet from 'helmet';import {rateLimit} from 'express-rate-limit';import * as oidc from 'openid-client';import {z} from 'zod';import {randomUUID,randomBytes} from 'node:crypto';import {readFileSync,existsSync} from 'node:fs';import path from 'node:path';import sanitize from 'sanitize-html';
import {query,init,search,indexArticle,postgres,transaction} from './db.mjs';import {scoreQuestions,levelFor,achievements} from './learning.mjs';
const aliases=existsSync('data/article-aliases.json')?JSON.parse(readFileSync('data/article-aliases.json','utf8')):{};
const prod=process.env.NODE_ENV==='production', port=Number(process.env.PORT||4317),origin=process.env.APP_URL||`http://localhost:${port}`;
if(prod&&(!process.env.SESSION_SECRET||process.env.SESSION_SECRET.length<32||!origin.startsWith('https://')))throw Error('Production requires HTTPS and SESSION_SECRET (32+ chars).');
await init();const now=()=>new Date().toISOString();const clean=(s)=>sanitize(s,{allowedTags:['h1','h2','h3','h4','p','br','ul','ol','li','strong','b','em','code','pre','table','thead','tbody','tr','td','th','blockquote','img','a','figure','figcaption'],allowedAttributes:{img:['src','alt','loading'],a:['href','target','rel']},allowedSchemes:['https','http'],transformTags:{img:(tag,attrs)=>({tagName:'img',attribs:{src:attrs.src?.startsWith('/media/')?attrs.src:'',alt:attrs.alt||'Иллюстрация из источника',loading:'lazy'}})}});
if(!postgres&&existsSync('data/catalog.json'))for(const a of JSON.parse(readFileSync('data/catalog.json','utf8'))){const found=await query('SELECT id FROM articles WHERE id=?',[a.id]);if(found.length)continue;await query('INSERT INTO articles(id,title,topic,body,html,images,source,source_name,status,role,sort_order,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',[a.id,a.title,a.topic,a.text,clean(a.html||''),JSON.stringify(a.images||[]),a.source,a.sourceName,a.status||'published',a.role||'Пользователь',a.sort_order||100,now()]);await indexArticle({id:a.id,title:a.title,body:a.text});}
if(!postgres&&existsSync('data/quests.json'))for(const q of JSON.parse(readFileSync('data/quests.json','utf8')))await query('INSERT INTO quests(id,title,topic,description,kind,status,questions,xp) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING',[q.id,q.title,q.topic,q.description,q.kind,q.status||'published',JSON.stringify(q.questions),q.xp]);
class Store extends session.Store{get(id,cb){query('SELECT data FROM sessions WHERE id=? AND expires_at>?',[id,now()]).then(r=>cb(null,r[0]?JSON.parse(r[0].data):null)).catch(cb);}set(id,s,cb){query('INSERT INTO sessions(id,data,expires_at) VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,expires_at=excluded.expires_at',[id,JSON.stringify(s),new Date(Date.now()+86400000*7).toISOString()]).then(()=>cb?.()).catch(cb);}destroy(id,cb){query('DELETE FROM sessions WHERE id=?',[id]).then(()=>cb?.()).catch(cb);}}
const app=express();app.disable('x-powered-by');app.use(helmet({contentSecurityPolicy:{directives:{defaultSrc:["'self'"],scriptSrc:["'self'"],styleSrc:["'self'","'unsafe-inline'"],imgSrc:["'self'",'data:'],connectSrc:["'self'",'ws://localhost:*'],objectSrc:["'none'"],upgradeInsecureRequests:prod?[]:null}},crossOriginEmbedderPolicy:false}));
app.use(express.json({limit:'2mb'}));app.use(rateLimit({windowMs:60000,limit:300,standardHeaders:true,legacyHeaders:false}));
app.use(session({name:'bregis.sid',secret:process.env.SESSION_SECRET||randomBytes(32).toString('hex'),resave:false,saveUninitialized:false,store:new Store(),cookie:{httpOnly:true,sameSite:'lax',secure:prod,maxAge:86400000*7}}));
app.use((req,res,next)=>{req.requestId=randomUUID();res.setHeader('X-Request-ID',req.requestId);if(req.path.startsWith('/api')||req.path.startsWith('/auth'))res.setHeader('Cache-Control','no-store');if(!['GET','HEAD','OPTIONS'].includes(req.method)&&req.headers.origin!==origin)return res.status(403).json({error:'Недопустимый источник запроса'});next();});
const requireUser=async(req,res,next)=>{const u=req.session.userId&&(await query('SELECT * FROM users WHERE id=?',[req.session.userId]))[0];if(!u)return res.status(401).json({error:'Войдите для сохранения результата'});req.user=u;next();};
const requireAdmin=(req,res,next)=>['admin','editor'].includes(req.user.role)?next():res.status(403).json({error:'Недостаточно прав'});
const audit=async(u,action,id)=>query('INSERT INTO audit(id,actor,action,entity,created_at) VALUES(?,?,?,?,?)',[randomUUID(),u,action,id,now()]);
app.get('/api/session',async(req,res)=>{let user=req.session.userId?(await query('SELECT id,name,role,public FROM users WHERE id=?',[req.session.userId]))[0]:null;res.json({user:user||null,local:!postgres&&!prod,google:Boolean(process.env.GOOGLE_CLIENT_ID&&process.env.GOOGLE_CLIENT_SECRET)});});
app.post('/api/local-login',async(req,res)=>{if(postgres||prod)return res.sendStatus(404);await query('INSERT INTO users(id,name,role,created_at) VALUES(?,?,?,?) ON CONFLICT(id) DO NOTHING',['local-learner','Локальный исследователь','admin',now()]);req.session.regenerate(err=>{if(err)return res.sendStatus(500);req.session.userId='local-learner';req.session.save(()=>res.json({ok:true}));});});
app.post('/api/logout',(req,res)=>req.session.destroy(()=>{res.clearCookie('bregis.sid');res.json({ok:true});}));
let googleConfig;async function google(){return googleConfig ||= await oidc.discovery(new URL('https://accounts.google.com'),process.env.GOOGLE_CLIENT_ID,process.env.GOOGLE_CLIENT_SECRET);}
app.get('/auth/google',async(req,res)=>{if(!process.env.GOOGLE_CLIENT_ID||!process.env.GOOGLE_CLIENT_SECRET)return res.redirect('/?auth=unconfigured');const cfg=await google();const verifier=oidc.randomPKCECodeVerifier(),state=oidc.randomState(),nonce=oidc.randomNonce();req.session.oauth={verifier,state,nonce,at:Date.now()};const url=oidc.buildAuthorizationUrl(cfg,{redirect_uri:origin+'/auth/google/callback',scope:'openid email profile',code_challenge:await oidc.calculatePKCECodeChallenge(verifier),code_challenge_method:'S256',state,nonce});req.session.save(()=>res.redirect(url.href));});
app.get('/auth/google/callback',async(req,res)=>{const flow=req.session.oauth;delete req.session.oauth;if(!flow||Date.now()-flow.at>600000)return res.status(400).send('Сессия входа истекла');const tokens=await oidc.authorizationCodeGrant(await google(),new URL(req.originalUrl,origin),{pkceCodeVerifier:flow.verifier,expectedState:flow.state,expectedNonce:flow.nonce,idTokenExpected:true});const claims=tokens.claims();if(!claims?.sub||!claims.email_verified)return res.status(403).send('Google не подтвердил аккаунт');const id='google:'+claims.sub;await query('INSERT INTO users(id,name,email,role,created_at) VALUES(?,?,?,?,?) ON CONFLICT(id) DO NOTHING',[id,String(claims.name||'Участник').slice(0,80),claims.email,claims.email===process.env.ADMIN_EMAIL?'admin':'user',now()]);req.session.regenerate(e=>{if(e)return res.sendStatus(500);req.session.userId=id;req.session.save(()=>res.redirect('/#profile'));});});
const knowledgeOutline=existsSync('data/knowledge-outline.json')?JSON.parse(readFileSync('data/knowledge-outline.json','utf8')):[];
const outlineById=new Map(knowledgeOutline.map(a=>[a.id,a]));
app.get('/api/knowledge-tree',async(req,res)=>{const published=await query("SELECT id,title,topic FROM articles WHERE status='published' ORDER BY sort_order,id");const byId=new Map(published.map(a=>[a.id,a]));res.json([...knowledgeOutline.filter(a=>byId.has(a.id)).map(a=>({...a,...byId.get(a.id)})),...published.filter(a=>!outlineById.has(a.id)).map(a=>({...a,module:a.topic,chapter:'Другие материалы'}))]);});
const manualSearch=existsSync('data/manual-search.json')?JSON.parse(readFileSync('data/manual-search.json','utf8')):[];
const normalizeSearch=s=>String(s).toLocaleLowerCase('ru').replaceAll('ё','е');
app.get('/api/search',async(req,res)=>{const q=normalizeSearch(String(req.query.q||'').trim().slice(0,160));if(!q)return res.json({items:[],total:0});const terms=q.split(/\s+/).filter(Boolean),offset=Math.max(0,Math.min(10000,Number(req.query.offset)||0));const articles=await query("SELECT id,title,body FROM articles WHERE status='published' AND topic='WebLab'");const hits=[...articles.map(a=>({...a,text:a.body,kind:'article',href:'/learn/'+a.id})),...manualSearch.map(p=>({...p,kind:'manual',href:'/#manual/lab/'+p.page}))].filter(a=>terms.every(t=>normalizeSearch(a.title+' '+a.text).includes(t))).map(a=>{const text=a.text,at=Math.max(0,normalizeSearch(text).indexOf(terms[0])-65);return{id:a.id,title:a.title,kind:a.kind,href:a.href,page:a.page,excerpt:(at?'…':'')+text.slice(at,at+260),rank:terms.reduce((sum,t)=>sum+(normalizeSearch(a.title).includes(t)?5:0),0)};}).sort((a,b)=>b.rank-a.rank||(a.page||0)-(b.page||0));res.json({items:hits.slice(offset,offset+30),total:hits.length});});
app.get('/api/catalog',async(req,res)=>{const q=String(req.query.q||'').slice(0,160),topic=String(req.query.topic||'');const items=await search(q,topic,Math.min(10000,Math.max(0,Number(req.query.offset)||0)));res.json({items:items.map(({body,html,...a})=>({...a,excerpt:body.slice(Math.max(0,body.toLowerCase().indexOf(q.toLowerCase())-60),Math.max(0,body.toLowerCase().indexOf(q.toLowerCase())-60)+230),images:JSON.parse(a.images)})),topics:await query("SELECT topic,COUNT(*) AS count FROM articles WHERE status='published' GROUP BY topic"),total:(await query("SELECT COUNT(*) AS n FROM articles WHERE status='published'"))[0].n});});
app.get('/api/articles/:id',async(req,res)=>{req.params.id=aliases[req.params.id]||req.params.id;const a=(await query("SELECT * FROM articles WHERE id=? AND status='published'",[req.params.id]))[0];if(!a)return res.status(404).json({error:'Материал не найден'});res.json({...a,...outlineById.get(a.id),title:a.title,images:JSON.parse(a.images)});});
app.post('/api/articles/:id/complete',requireUser,async(req,res)=>{if(!(await query("SELECT id FROM articles WHERE id=? AND status='published'",[req.params.id])).length)return res.sendStatus(404);await query('INSERT INTO progress(user_id,article_id,completed_at) VALUES(?,?,?) ON CONFLICT(user_id,article_id) DO NOTHING',[req.user.id,req.params.id,now()]);res.json({ok:true});});
const curriculum=existsSync('data/curriculum.json')?JSON.parse(readFileSync('data/curriculum.json','utf8')):[];
const curriculumMap=new Map(curriculum.map(q=>[q.id,q]));
app.get('/api/quests',async(req,res)=>res.json((await query("SELECT * FROM quests WHERE status='published'")).map(({questions,...q})=>({...q,...curriculumMap.get(q.id),count:JSON.parse(questions).length}))));
app.post('/api/quests/:id/start',requireUser,async(req,res)=>{const q=(await query("SELECT * FROM quests WHERE id=? AND status='published'",[req.params.id]))[0];if(!q)return res.sendStatus(404);let a=(await query('SELECT * FROM attempts WHERE user_id=? AND quest_id=? AND completed_at IS NULL ORDER BY created_at DESC LIMIT 1',[req.user.id,q.id]))[0];if(!a){a={id:randomUUID(),snapshot:q.questions,answers:'[]'};await query('INSERT INTO attempts(id,user_id,quest_id,version,snapshot,created_at) VALUES(?,?,?,?,?,?)',[a.id,req.user.id,q.id,q.version,q.questions,now()]);}res.json({id:a.id,title:q.title,questions:JSON.parse(a.snapshot).map(({answer,explanation,...x})=>x),answers:JSON.parse(a.answers)});});
app.put('/api/attempts/:id',requireUser,async(req,res)=>{const answers=z.array(z.union([z.number().int(),z.array(z.number().int()),z.null()])).max(100).parse(req.body.answers);await query('UPDATE attempts SET answers=? WHERE id=? AND user_id=? AND completed_at IS NULL',[JSON.stringify(answers),req.params.id,req.user.id]);res.json({ok:true});});

app.post('/api/attempts/:id/finish',requireUser,rateLimit({windowMs:60000,limit:20}),async(req,res)=>{
 const response=await transaction(async()=>{
 const a=(await query('SELECT * FROM attempts WHERE id=? AND user_id=?'+(postgres?' FOR UPDATE':''),[req.params.id,req.user.id]))[0];
 if(!a)return null;
 const result=scoreQuestions(JSON.parse(a.snapshot),JSON.parse(a.answers));
 const q=(await query('SELECT * FROM quests WHERE id=?',[a.quest_id]))[0];
 await query('UPDATE attempts SET score=?,completed_at=COALESCE(completed_at,?) WHERE id=?',[result.score,now(),a.id]);
 if(result.score>=80)await query('INSERT INTO xp_events(id,user_id,source,amount,created_at) VALUES(?,?,?,?,?) ON CONFLICT(user_id,source) DO NOTHING',[randomUUID(),req.user.id,'quest:'+q.id+':'+a.version,q.xp,now()]);
 return {...result,xp:result.score>=80?q.xp:0,note:'XP за версию квеста начисляется один раз при результате от 80%.'};
 });if(!response)return res.sendStatus(404);res.json(response);
});
app.get('/api/profile',requireUser,async(req,res)=>{const xp=Number((await query('SELECT COALESCE(SUM(amount),0) AS n FROM xp_events WHERE user_id=?',[req.user.id]))[0].n);const progress=await query('SELECT article_id,completed_at FROM progress WHERE user_id=?',[req.user.id]);const attempts=await query('SELECT a.id,a.score,a.completed_at,q.title FROM attempts a JOIN quests q ON q.id=a.quest_id WHERE a.user_id=? ORDER BY a.created_at DESC',[req.user.id]);res.json({user:{name:req.user.name,role:req.user.role,public:req.user.public},xp,level:levelFor(xp),next:100*levelFor(xp)**2,progress,attempts,achievements:achievements(xp,attempts.filter(a=>a.completed_at).length,progress.length)});});
app.patch('/api/profile',requireUser,async(req,res)=>{const b=z.object({name:z.string().trim().min(2).max(60),public:z.boolean()}).parse(req.body);await query('UPDATE users SET name=?,public=? WHERE id=?',[b.name,b.public?1:0,req.user.id]);res.json({ok:true});});
app.get('/api/profile/export',requireUser,async(req,res)=>{res.attachment('bregis-profile.json').json({profile:req.user,progress:await query('SELECT * FROM progress WHERE user_id=?',[req.user.id]),attempts:await query('SELECT id,quest_id,answers,score,created_at,completed_at FROM attempts WHERE user_id=?',[req.user.id]),xp:await query('SELECT * FROM xp_events WHERE user_id=?',[req.user.id])});});
app.delete('/api/profile',requireUser,async(req,res)=>{await query('DELETE FROM users WHERE id=?',[req.user.id]);req.session.destroy(()=>res.json({ok:true}));});
app.get('/api/ranking',async(req,res)=>{const since=req.query.period==='month'?new Date(Date.UTC(new Date().getUTCFullYear(),new Date().getUTCMonth(),1)).toISOString():'1970';const rows=await query("SELECT u.name,u.id,COALESCE(SUM(x.amount),0) AS xp FROM users u JOIN xp_events x ON x.user_id=u.id WHERE u.public=1 AND u.id<>'local-learner' AND x.created_at>=? GROUP BY u.id,u.name ORDER BY xp DESC,u.id LIMIT 100",[since]);res.json(rows.map((x,i)=>({name:x.name,xp:Number(x.xp),level:levelFor(Number(x.xp)),rank:i+1})));});
app.get('/api/admin/articles',requireUser,requireAdmin,async(req,res)=>res.json(await query('SELECT id,title,topic,status,version FROM articles ORDER BY updated_at DESC')));
app.get('/api/admin/articles/:id',requireUser,requireAdmin,async(req,res)=>res.json((await query('SELECT * FROM articles WHERE id=?',[req.params.id]))[0]));
app.put('/api/admin/articles/:id',requireUser,requireAdmin,async(req,res)=>{const b=z.object({title:z.string().min(3).max(200),body:z.string().min(10).max(150000),topic:z.string().min(2).max(80),status:z.enum(['draft','review','published','archived']),version:z.number().int()}).parse(req.body);if(req.user.role!=='admin'&&b.status==='published')return res.sendStatus(403);const a=(await query('SELECT * FROM articles WHERE id=?',[req.params.id]))[0];if(!a||a.version!==b.version)return res.status(409).json({error:'Материал изменён. Обновите страницу.'});const rows=await query('UPDATE articles SET title=?,body=?,topic=?,status=?,html=?,version=version+1,updated_at=? WHERE id=? AND version=? RETURNING *',[b.title,b.body,b.topic,b.status,'',now(),a.id,b.version]);if(!rows.length)return res.status(409).json({error:'Конфликт версии'});await query('INSERT INTO article_versions(id,article_id,version,snapshot,actor,created_at) VALUES(?,?,?,?,?,?)',[randomUUID(),a.id,a.version,JSON.stringify(a),req.user.id,now()]);await indexArticle(rows[0]);await audit(req.user.id,'article.update',a.id);res.json(rows[0]);});
app.post('/api/admin/articles',requireUser,requireAdmin,async(req,res)=>{const id='article-'+randomUUID();await query('INSERT INTO articles(id,title,topic,body,source,source_name,status,updated_at) VALUES(?,?,?,?,?,?,?,?)',[id,'Новый материал','WebLab','Добавьте проверенный текст инструкции.','','Редактор','draft',now()]);await audit(req.user.id,'article.create',id);res.json({id});});
app.get('/api/admin/audit',requireUser,requireAdmin,async(req,res)=>res.json(await query('SELECT action,entity,created_at FROM audit ORDER BY created_at DESC LIMIT 100')));


app.post('/api/admin/questions',requireUser,requireAdmin,async(req,res)=>{const b=z.object({prompt:z.string().max(2000).optional(),options:z.array(z.string().max(2000)).min(2).max(20).optional()}).parse(req.body||{});const id='quest-'+randomUUID();const qs=[{type:'single',prompt:b.prompt||'Новый вопрос',options:b.options||['Вариант 1','Вариант 2'],answer:-1,explanation:'',source:'wiki-root'}];await query('INSERT INTO quests(id,title,topic,description,kind,status,questions,xp) VALUES(?,?,?,?,?,?,?,?)',[id,b.prompt?.slice(0,140)||'Новая практика','WebLab','Добавьте описание и подтвердите ключ ответов.','test','draft',JSON.stringify(qs),100]);await audit(req.user.id,'quest.create',id);res.json({id});});
app.get('/api/admin/questions' ,requireUser,requireAdmin,async(req,res)=>res.json(await query('SELECT * FROM quests ORDER BY title')));
const questionSchema=z.object({type:z.enum(['single','multiple','order']),prompt:z.string().min(5).max(2000),scenario:z.string().max(3000).optional(),options:z.array(z.string().min(1).max(2000)).min(2).max(20),answer:z.union([z.number().int().nonnegative(),z.array(z.number().int().nonnegative())]),explanation:z.string().min(10).max(5000),source:z.string().min(1)}).superRefine((q,ctx)=>{const a=Array.isArray(q.answer)?q.answer:[q.answer];if(a.some(v=>v>=q.options.length)||new Set(a).size!==a.length||!a.length||q.type==='single'&&Array.isArray(q.answer)||q.type!=='single'&&!Array.isArray(q.answer)||q.type==='order'&&a.length!==q.options.length)ctx.addIssue({code:'custom',message:'Некорректный ключ ответов'});});
app.put('/api/admin/questions/:id',requireUser,requireAdmin,async(req,res)=>{const b=z.object({title:z.string().min(3).max(150),description:z.string().min(5).max(2000),topic:z.string().min(2).max(80),kind:z.enum(['test','order','scenario']),status:z.enum(['draft','published','archived']),xp:z.number().int().min(10).max(500),version:z.number().int(),questions:z.array(questionSchema).min(1).max(100)}).parse(req.body);if(req.user.role!=='admin'&&b.status==='published')return res.sendStatus(403);for(const q of b.questions)if(!(await query("SELECT id FROM articles WHERE id=? AND status='published'",[q.source])).length)return res.status(400).json({error:'Каждый вопрос должен ссылаться на опубликованный источник'});const rows=await query('UPDATE quests SET title=?,description=?,topic=?,kind=?,status=?,xp=?,questions=?,version=version+1 WHERE id=? AND version=? RETURNING id',[b.title,b.description,b.topic,b.kind,b.status,b.xp,JSON.stringify(b.questions),req.params.id,b.version]);if(!rows.length)return res.status(409).json({error:'Конфликт версии'});await audit(req.user.id,'quest.update',req.params.id);res.json({ok:true});});
app.get('/api/admin/question-drafts',requireUser,requireAdmin,(req,res)=>res.json(existsSync('data/question-drafts.json')?JSON.parse(readFileSync('data/question-drafts.json','utf8')):[]));
app.get('/api/admin/articles/:id/history',requireUser,requireAdmin,async(req,res)=>res.json(await query('SELECT version,snapshot,created_at FROM article_versions WHERE article_id=? ORDER BY version DESC',[req.params.id])));
app.get('/api/stats',async(req,res)=>res.json({participants:Number((await query("SELECT COUNT(*) AS n FROM users WHERE id<>'local-learner'"))[0].n),completed:Number((await query('SELECT COUNT(*) AS n FROM attempts WHERE completed_at IS NOT NULL'))[0].n),materials:Number((await query("SELECT COUNT(*) AS n FROM articles WHERE status='published'"))[0].n)}));
app.get('/api/health' ,async(req,res)=>{await query('SELECT 1');res.json({status:'ok'});});
app.get('/robots.txt',(req,res)=>res.type('text').send(prod?'User-agent: *\nDisallow: /api/\nDisallow: /auth/\n':'User-agent: *\nDisallow: /\n'));
if(prod&&process.env.CONTENT_PUBLICATION_APPROVED!=='yes')throw Error('Content requires review before public hosting.');
app.use('/media',express.static('public/media'));app.use('/manuals',express.static('public/manuals'));app.use(express.static('public'));
if(existsSync('dist/index.html')){app.use(express.static('dist'));
 const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 app.get('/sitemap.xml',async(req,res)=>{const rows=await query("SELECT id,updated_at FROM articles WHERE status='published'");res.type('application/xml').send('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+rows.map(a=>'<url><loc>'+escape(origin+'/learn/'+encodeURIComponent(a.id))+'</loc><lastmod>'+a.updated_at.slice(0,10)+'</lastmod></url>').join('')+'</urlset>');});
 app.get('/learn/:id',async(req,res)=>{if(aliases[req.params.id])return res.redirect('/learn/'+aliases[req.params.id]);const meta=outlineById.get(req.params.id);if(meta?.topic==='Брегис Лаборатория')return res.redirect('/#manual/lab/'+(meta.page||13));const a=(await query("SELECT * FROM articles WHERE id=? AND status='published'",[req.params.id]))[0];if(!a)return res.status(404).type('html').send('<h1>Материал не найден</h1><a href="/">Вернуться в академию</a>');let doc=readFileSync('dist/index.html','utf8').replace('<title>BREGIS — Академия лабораторных систем</title>','<title>'+escape(a.title)+' — BREGIS</title>').replace('</head>','<link rel="canonical" href="'+escape(origin+'/learn/'+encodeURIComponent(a.id))+'"/><meta property="og:title" content="'+escape(a.title)+'"/></head>').replace('<div id="root"></div>','<div id="root"><main><h1>'+escape(a.title)+'</h1><article>'+(a.html||'<p>'+escape(a.body)+'</p>')+'</article></main></div>');res.type('html').send(doc);});
 app.get('/',async(req,res)=>{const rows=await query("SELECT id,title FROM articles WHERE status='published' ORDER BY sort_order,title LIMIT 40");let doc=readFileSync('dist/index.html','utf8').replace('<div id="root"></div>','<div id="root"><main><h1>BREGIS — Академия лабораторных систем</h1><p>Руководства, практика и обучение работе с ЛИС.</p><ul>'+rows.map(a=>'<li><a href="/learn/'+encodeURIComponent(a.id)+'">'+escape(a.title)+'</a></li>').join('')+'</ul></main></div>');res.type('html').send(doc);});
 app.get('/{*path}',(req,res)=>res.status(404).send('Страница не найдена'));
}else{const {createServer}=await import('vite');const vite=await createServer({server:{middlewareMode:true},appType:'spa'});app.use(vite.middlewares);}
app.use((err,req,res,next)=>{console.error(JSON.stringify({level:'error',id:req.requestId,type:err.name}));res.status(err.name==='ZodError'?400:500).json({error:err.name==='ZodError'?'Проверьте введённые данные':'Не удалось выполнить действие. Повторите позже.',requestId:req.requestId});});
app.listen(port,'127.0.0.1',()=>console.log(`BREGIS local: ${origin}`));
