import React,{useEffect,useLayoutEffect,useMemo,useRef,useState}from'react';
import{getDocument,GlobalWorkerOptions,TextLayer}from'pdfjs-dist';
import workerUrl from 'pdfjs-dist/build/pdf.worker.min.mjs?url';
import{PDF_WIDTH,CROP_TOP,CROP_BOTTOM,FIRST_PAGE,PAGE_GAP,pageHeight,pageTop,readingPosition,jumpOffset,visiblePages,sectionVisibility}from'./manual-layout.mjs';
GlobalWorkerOptions.workerSrc=workerUrl;

// Each visible page owns its render task. Distant canvases are unmounted, while
// fixed-size slots preserve the full document's scroll range and position.
function PdfSheet({doc,number,scale}){const canvas=useRef(null),text=useRef(null),[busy,setBusy]=useState(true),[error,setError]=useState('');
 useEffect(()=>{let cancelled=false,renderTask,layer;setBusy(true);setError('');
  (async()=>{try{const pdfPage=await doc.getPage(number);if(cancelled)return;const base=pdfPage.getViewport({scale:1}),viewport=pdfPage.getViewport({scale}),ratio=Math.min(window.devicePixelRatio||1,2),element=document.createElement('canvas');element.width=Math.ceil(viewport.width*ratio);element.height=Math.ceil(pageHeight(scale)*ratio);element.style.width=viewport.width+'px';element.style.height=pageHeight(scale)+'px';renderTask=pdfPage.render({canvasContext:element.getContext('2d'),viewport,transform:[ratio,0,0,ratio,0,-CROP_TOP*scale*ratio]});await renderTask.promise;if(cancelled)return;canvas.current.replaceChildren(element);const content=await pdfPage.getTextContent();if(cancelled)return;const container=document.createElement('div');container.className='manual-text-layer';container.style.setProperty('--scale-factor',scale);container.style.setProperty('--total-scale-factor',scale);container.style.width=viewport.width+'px';container.style.height=viewport.height+'px';container.style.top=-CROP_TOP*scale+'px';text.current.replaceChildren(container);layer=new TextLayer({textContentSource:{...content,items:content.items.filter(item=>!item.transform||(base.height-item.transform[5]>=CROP_TOP&&base.height-item.transform[5]<CROP_BOTTOM))},container,viewport});await layer.render();if(!cancelled)setBusy(false);
  }catch(e){if(!cancelled&&e.name!=='RenderingCancelledException'){setError('Не удалось отобразить страницу '+number+'. '+e.message);setBusy(false);}}})();
  return()=>{cancelled=true;renderTask?.cancel();layer?.cancel();};
 },[doc,number,scale]);
 return <div className="manual-page" data-page={number} aria-label={'Страница руководства '+number} aria-busy={busy} style={{width:PDF_WIDTH*scale,height:pageHeight(scale)}}><div ref={canvas}/><div className="manual-text-host" ref={text}/>{busy&&<span className="manual-loading">Загрузка страницы {number}…</span>}{error&&<p role="alert" className="manual-render-error">{error}</p>}</div>;
}

export default function ManualReader({pageNumber=13,sectionIndex}){const[doc,setDoc]=useState(null),[toc,setToc]=useState([]),[find,setFind]=useState(''),[zoom,setZoom]=useState(1),[width,setWidth]=useState(700),[height,setHeight]=useState(700),[scroll,setScroll]=useState(0),[error,setError]=useState(''),[input,setInput]=useState(String(pageNumber)),[outlineOpen,setOutlineOpen]=useState(true);const host=useRef(null),outlineRef=useRef(null),frame=useRef(0),layoutRef=useRef(null),navReady=useRef(false);const lastPage=doc?.numPages||331,scale=width/PDF_WIDTH*zoom,current=readingPosition(scroll+20,scale,lastPage),range=visiblePages(scroll,height,scale,lastPage),sections=useMemo(()=>sectionVisibility(toc,scroll,height,scale),[toc,scroll,height,scale]),visibleSet=new Set(sections.visible);
 useEffect(()=>{let active=true;const task=getDocument({url:'/manuals/lab.pdf',isEvalSupported:false});task.promise.then(d=>active&&setDoc(d)).catch(e=>active&&setError('Не удалось открыть руководство. '+e.message));fetch('/manuals/lab-toc.json').then(r=>{if(!r.ok)throw Error('Оглавление недоступно');return r.json();}).then(d=>active&&setToc(d)).catch(e=>active&&setError(e.message));return()=>{active=false;task.destroy();};},[]);
 useEffect(()=>{const observer=new ResizeObserver(entries=>{setWidth(Math.max(240,entries[0].contentRect.width));setHeight(entries[0].target.clientHeight);});if(host.current)observer.observe(host.current);return()=>{observer.disconnect();cancelAnimationFrame(frame.current);};},[]);
 const sync=()=>{cancelAnimationFrame(frame.current);frame.current=requestAnimationFrame(()=>{if(host.current)setScroll(Math.max(0,host.current.scrollTop-16));});};
 // Preserve the same PDF coordinate when the reader width or zoom changes.
 useLayoutEffect(()=>{const previous=layoutRef.current;layoutRef.current={scale};if(previous&&navReady.current&&host.current&&previous.scale!==scale){const anchor=readingPosition(Math.max(0,host.current.scrollTop-16),previous.scale,lastPage);const top=jumpOffset(anchor.page,anchor.y,scale,lastPage);host.current.scrollTop=top+16;setScroll(top);}},[scale,lastPage]);
 const jump=(number,index)=>{const target=toc[index],page=Math.min(lastPage,Math.max(FIRST_PAGE,Number(number)||13)),y=target?.page===page?target.y:CROP_TOP;const top=Math.max(0,jumpOffset(page,y,scale,lastPage)-8);if(host.current){host.current.scrollTo({top:top+16,left:0,behavior:'instant'});setScroll(top);}navReady.current=true;};
 useEffect(()=>{if(doc&&toc.length)jump(pageNumber,sectionIndex);},[doc,toc,pageNumber,sectionIndex]);
 useEffect(()=>setInput(String(current.page)),[current.page]);
 useEffect(()=>{const panel=outlineRef.current,link=panel?.querySelector('[aria-current="location"]');if(!link)return;const box=link.getBoundingClientRect(),bounds=panel.getBoundingClientRect();if(box.top<bounds.top+100||box.bottom>bounds.bottom-12)panel.scrollTop+=box.top-bounds.top-130;},[sections.active,outlineOpen]);
 const navigate=(number,index)=>{jump(number,index);location.hash='manual/lab/'+Math.min(lastPage,Math.max(FIRST_PAGE,Number(number)||13))+(index===undefined?'':'/'+index);};
 const matches=toc.map((t,index)=>({...t,index})).filter(t=>!find||t.title.toLowerCase().includes(find.toLowerCase()));const activeTitle=toc[sections.active]?.title||'Руководство пользователя';const pages=Array.from({length:Math.max(0,range.last-range.first+1)},(_,i)=>range.first+i);
 return <section className="manual-reader"><div className="manual-heading"><div><span className="eyebrow">РУКОВОДСТВО // НЕПРЕРЫВНОЕ ЧТЕНИЕ</span><h1>Руководство ЛИС</h1><p>Листайте документ целиком или выбирайте тему в оглавлении. Обложка и колонтитулы скрыты.</p></div><a className="outline-button" href="/manuals/lab.pdf" target="_blank" rel="noreferrer">Открыть PDF ↗</a></div>
 <div className="manual-toolbar"><button onClick={()=>setOutlineOpen(!outlineOpen)} aria-expanded={outlineOpen}>☰ Оглавление</button><button disabled={current.page<=FIRST_PAGE} onClick={()=>navigate(current.page-1)} aria-label="Предыдущая страница">←</button><form onSubmit={e=>{e.preventDefault();navigate(input);}}><label>Страница <input aria-label="Номер страницы PDF" type="number" min={FIRST_PAGE} max={lastPage} value={input} onChange={e=>setInput(e.target.value)}/></label><span> / {lastPage}</span><button type="submit">Перейти</button></form><button disabled={current.page>=lastPage} onClick={()=>navigate(current.page+1)} aria-label="Следующая страница">→</button><button disabled={zoom<=.75} onClick={()=>setZoom(z=>Math.max(.75,z-.25))} aria-label="Уменьшить масштаб">−</button><span>{Math.round(zoom*100)}%</span><button disabled={zoom>=2} onClick={()=>setZoom(z=>Math.min(2,z+.25))} aria-label="Увеличить масштаб">+</button><button onClick={()=>setZoom(1)}>По ширине</button></div>
 <div className={'manual-layout '+(!outlineOpen?'outline-hidden':'')}>
 {outlineOpen&&<aside className="manual-outline" ref={outlineRef}><div className="manual-outline-search"><label>Найти тему<input placeholder="Название раздела…" value={find} onChange={e=>setFind(e.target.value)}/></label><p>{matches.length} пунктов · подсветка по прокрутке</p></div><nav aria-label="Оглавление PDF">{matches.map(t=><a key={t.index} href={'#manual/lab/'+t.page+'/'+t.index} onClick={e=>{e.preventDefault();navigate(t.page,t.index);}} style={{'--depth':Math.min(t.level,4)-1}} className={(t.level===1?'module ':'')+(sections.active===t.index?'current':visibleSet.has(t.index)?'in-view':'')} aria-current={sections.active===t.index?'location':undefined}><span>{t.code} {t.title}</span><small>{t.page}</small></a>)}</nav>{!matches.length&&<p>Темы не найдены.</p>}</aside>}
 <div className="manual-document"><div className="manual-page-label">{activeTitle} · стр. {current.page}</div><div className="manual-canvas-scroll continuous-scroll" ref={host} onScroll={sync} tabIndex="0" role="region" aria-label="Непрерывный документ Лаборатории">{error&&<p role="alert" className="error">{error}</p>}{!doc&&<div className="manual-loading" role="status">Открываем руководство…</div>}<div className="manual-page-stack" style={{height:(lastPage-FIRST_PAGE+1)*(pageHeight(scale)+PAGE_GAP)-PAGE_GAP,width:PDF_WIDTH*scale}}>{doc&&pages.map(number=><div className="manual-page-slot" key={number} style={{position:'absolute',top:pageTop(number,scale),width:PDF_WIDTH*scale,height:pageHeight(scale)}}><PdfSheet doc={doc} number={number} scale={scale}/></div>)}</div></div><div className="manual-bottom"><span>Непрерывная лента · стр. {current.page} из {lastPage}</span><span className="manual-auto-follow">● Оглавление следует за текстом</span></div></div></div></section>;
}
